application: projectchooser
version: 1
runtime: python
api_version: 1

handlers:
- url: /bootstrap
  static_dir: static/bootstrap
  
- url: /js
  static_dir: static/js

- url: /.*
  script: main.py
  
builtins:
- datastore_admin: on