application: projectchooser
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /api/.*
  script: app/APIDispatcher.py
  login: required
  auth_fail_action: unauthorized

- url: /.*
  script: main.py
  login: required