application: projectchooser
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Base static mapping (handles all static file requests)
- url: /static
  static_dir: static

# Backend Database mapping (handles all calls to the admin scripts)
- url: /doAdminAction
  script: admin.AdminDispatcher.adminDispatcher

# Backend API mapping (handles all calls to the API)
- url: /api/.*
  script: app.APIDispatcher.apiDispatcher

# Front end Database mappings (gives an entry point to the admin backend)
- url: /admin
  static_files: static/admin.html
  upload: static/admin.html

- url: /proposals
  static_files: static/proposals.html
  upload: static/proposals.html

- url: /apidemo
  static_files: static/RestApiTest.html
  upload: static/RestApiTest.html

- url: /signup
  static_files: static/signup.html
  upload: static/signup.html

# Front end index mapping (main starting point of the application)
- url: /|/index.html
  static_files: static/dashboard.html
  upload: static/dashboard.html